name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
      
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          curl -fsSL https://deno.land/x/install/install.sh | DENO_INSTALL=/usr/local sh
          sudo apt-get install -y ruby-full git g++ cmake pkg-config libssl-dev
          gem install licensed

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        
      - uses: lowlighter/metrics@main
        with:
          token: ${{ secrets.metrics }}

